name: Pylint

# This workflow runs pylint on Python files whenever there is a push event.

on:
  push:
    branches:
      - master # Default branch

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']

    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE, so the job can access it
      - name: Checkout code
        uses: actions/checkout@v4

      # Sets up the Python environment
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      # Installs required dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 pylint

      # Runs pylint on Python files
      - name: Analysing the code with pylint
        run: |
          pylint $(git ls-files '*.py')
